apiVersion: v1
kind: ConfigMap
metadata:
  name: html-files-server
  namespace: default
data:
  nginx.conf: |
    server {
      listen 8080;
      location / {
        root /html;
        autoindex on;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-server
  template:
    metadata:
      labels:
        app: html-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html
          mountPath: /html
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: html
        configMap:
          name: vm-html-files
      - name: config
        configMap:
          name: html-files-server
---
apiVersion: v1
kind: Service
metadata:
  name: html-server
  namespace: default
spec:
  selector:
    app: html-server
  ports:
  - port: 80
    targetPort: 8080
