apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-landing-nodeport
    namespace: default
    labels:
      demo: multiarch
  spec:
    type: NodePort
    selector:
      app: multiarch-landing
    ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-s390x-nodeport
    namespace: default
    labels:
      demo: multiarch
  spec:
    type: NodePort
    selector:
      kubevirt.io/domain: fedora-s390x
    ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-x86-nodeport
    namespace: default
    labels:
      demo: multiarch
  spec:
    type: NodePort
    selector:
      kubevirt.io/domain: fedora-x86
    ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082
