apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-demo-2
  namespace: default
  labels:
    app: webserver-demo
    arch: s390x
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-demo-2
        app: webserver-demo
    spec:
      nodeSelector:
        kubernetes.io/arch: s390x
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
            runcmd:
              - [ systemctl, enable, --now, sshd ]
